default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/felixOlesen/Spec-Tagger/
    rev: v0.0.2
    hooks:
      - id: spectagger-tag-check
        args: [--target_spec, features, --test_dir, tests,
               --test_command, "pytest {tests}"]
      - id: spectagger-run
        args: [--target_spec, features, --test_dir, tests,
               --test_command, "pytest {tests}"]
