PYTHON_STOPWORDS = {
    "self",
    "true",
    "false",
    "none",
    "null",
    "returnvalue",
    "item",
    "data",
    "test",
    "assert",
    "result",
    "args",
    "kwargs",
    "type",
    "list",
    "dict",
    "str",
    "int",
    "bool",
    "get",
    "set",
    "add",
    "new",
    "old",
    "the",
    "and",
    "for",
    "not",
}

RUBY_STOPWORDS = {
    "def",
    "end",
    "class",
    "module",
    "self",
    "nil",
    "true",
    "false",
    "and",
    "not",
    "then",
    "elsif",
    "unless",
    "while",
    "until",
    "begin",
    "rescue",
    "ensure",
    "yield",
    "super",
    "return",
    "require",
    "require_relative",
    "include",
    "extend",
    "attr_accessor",
    "attr_reader",
    "attr_writer",
    "private",
    "protected",
    "public",
    "raise",
    "lambda",
    "proc",
    "block",
    "each",
    "map",
    "select",
    "reject",
    "new",
    "call",
    "send",
    "respond_to",
    "to_s",
    "to_i",
    "to_a",
    "to_h",
    "inspect",
    "freeze",
    "dup",
    "clone",
    "hash",
    "eql",
    "nil?",
    "empty",
    "sizelength",
    "first",
    "last",
    "push",
    "pop",
    "key",
    "keys",
    "values",
    "count",
    "sort",
    "describe",
    "context",
    "it",
    "specify",
    "before",
    "after",
    "around",
    "let",
    "subject",
    "expect",
    "should",
    "shall",
    "allow",
    "receive",
    "double",
    "instance_double",
    "stub",
    "mock",
    "eq",
    "eql",
    "match",
    "include",
    "assert",
    "refute",
    "assert_equal",
    "refute_equal",
    "setup",
    "teardown",
    "test",
    "spec",
    "example",
    "scenario",
    "given",
    "when",
    "then",
    "step",
}
QUERIES = {
    "python": """ 
        (function_definition name: (identifier) @sym)
        (class_definition    name: (identifier) @sym)
        (string_content) @text 
    """,
    "ruby": """
        (method name: (identifier) @sym)
        (class name: (constant) @sym)
        (string (string_content) @text)
    """,
}

EXT_TO_LANG = {".py": "python", ".rb": "ruby"}
